<div class="footer">
  <div class="footer_upper">
    <div class="footer_upper_in">
      <ul class="footer_menu">
        <li><a href="./">HOME</a></li>
        <li><a href="./company.php">COMPANY</a></li>
        <li><a href="./contact.php">CONTACT</a></li>
        <li><a href="./privacy.php">PRIVACY POLICY</a></li>
      </ul>
    </div>
  </div>
  <div class="footer_lower">
    <div class="footer_lower_in">
      <div class="footer_copy">©KAIZEN.TEC INC. ALL RIGHTS RESERVED.</div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="./js/actions.js"></script>


