<div class="header">
  <div class="header_logo">
    <a href="./">KAIZEN.TECH</a>
  </div>
</div>

<div class="menu_button only_sp">
  <button class="menu-trigger">
    <span></span>
    <span></span>
    <span></span>
  </button>
</div>

<div class="header_menu_wrap">
  <div class="header_menu_wrap_in">
    <div class="header_menu_logo only_sp">
      <a href="./">KAIZEN.TECH</a>
    </div>
    <ul class="header_menu">
      <li><a href="./">HOME</a></li>
      <li><a href="./company.php">COMPANY</a></li>
      <li><a href="./contact.php">CONTACT</a></li>
      <li><a href="./privacy.php">PRIVACY POLICY</a></li>
    </ul>
  </div>
</div>
